// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// CLI/schema-engine commands (migrate dev/deploy, db push, studio) use
// DIRECT_URL, the unpooled connection — migrations take advisory locks and
// run DDL, which doesn't play well through a transaction-mode pooler like
// PgBouncer. The app's runtime PrismaClient (src/lib/prisma.ts) uses the
// separate pooled DATABASE_URL instead. Locally both can point at the same
// database; in production point them at your provider's direct vs. pooled
// connection strings respectively.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
